### ISSUE TITLE
sudo for registry pull

### ISSUE THREAD

**Issue by astlock** [veertuinc/anka-vm-github-action#19]
I tried an action but as expected I got an error because you need to use sudo to pull from the registry. 
How do I need to put the sudo there, or maybe some other more correct way exists?

```
Run veertuinc/anka-vm-github-action@v1.3.2
  with:
    anka-vm-template-name: big-sur-test
    anka-vm-tag-name: latest
    anka-run-options: --env
    vm-commands: echo \"Starting build process on \$(hostname)\"
  uname -a && \
  ls -la ls -la /Users/anka/Downloads
  
    artifact-files: log.txt
  build/binaryfile-v1
  
Anka Virtualization CLI found at: /usr/local/bin/anka
Created /tmp/registry-pull-lock-big-sur-test!
Preparing Anka VM (Template: big-sur-test, Tag: latest)
/usr/local/bin/bash -c anka registry pull  big-sur-test -t latest
-anka: No registry configured
Deleted /tmp/registry-pull-lock-big-sur-test!
Error: Error: registry pull failed:
Error: exec.exec failed:
STDOUT: -anka: No registry configured
Error: The process '/usr/local/bin/bash' failed with exit code 30
    at ExecState._setResult (/Users/astlock/Downloads/anka/actions-runner/_work/_actions/veertuinc/anka-vm-github-action/v1.3.2/dist/index.js:942:25)
    at ExecState.CheckComplete (/Users/astlock/Downloads/anka/actions-runner/_work/_actions/veertuinc/anka-vm-github-action/v1.3.2/dist/index.js:925:18)
    at ChildProcess.<anonymous> (/Users/astlock/Downloads/anka/actions-runner/_work/_actions/veertuinc/anka-vm-github-action/v1.3.2/dist/index.js:819:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
    at Object.hostCommands (/Users/astlock/Downloads/anka/actions-runner/_work/_actions/veertuinc/anka-vm-github-action/v1.3.2/dist/index.js:1058:11)
    at Object.ankaRegistryPull (/Users/astlock/Downloads/anka/actions-runner/_work/_actions/veertuinc/anka-vm-github-action/v1.3.2/dist/index.js:6152:13)
```

**Comment by astlock** [comment]
Ok, seems there is no way to put forward sudo before `anki registry pull`, so I need your help with this. Thanks!
https://github.com/veertuinc/anka-vm-github-action/blob/6873084a4aaa9eca9e6e0f5597321f162d0bc830/prepare.js#L65

**Comment by NorseGaud** [comment]
Hi, so the action runs as the currently logged in user and doesn't need sudo at all. You'll want to anka registry add and configure the registry on the user and then the action should work just fine.

**Comment by astlock** [comment]
yeah, just found it right after my post ^. Just need to add a registry without sudo.  Sorry for disturbing you.
